modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"
issueTrackerURL="https://github.com/createtiers/createtiers/issues"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
authors="${mod_authors}"
description="${mod_description}"
logoFile="createtiers.png"

[[dependencies.createtiers]]
modId="forge"
mandatory=true
versionRange="[47,)"
ordering="NONE"
side="BOTH"

[[dependencies.createtiers]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1,1.21)"
ordering="NONE"
side="BOTH"

[[dependencies.createtiers]]
modId="create"
mandatory=true
versionRange="[6.0,7.0)"
ordering="AFTER"
side="BOTH"
