package com.createtiers.client;

import com.createtiers.CreateTiers;
import com.createtiers.api.Tier;
import com.createtiers.api.TierRegistry;
import com.google.gson.JsonArray;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParser;
import net.minecraft.core.Direction;
import net.minecraft.resources.ResourceLocation;
import net.minecraftforge.api.distmarker.Dist;
import net.minecraftforge.api.distmarker.OnlyIn;

import java.io.InputStreamReader;
import java.nio.charset.StandardCharsets;
import java.util.HashMap;
import java.util.Map;
import java.util.Set;
import java.util.Collections;

/**
 * Generates tiered blockstates and models dynamically.
 * Models are generated by mutating Create's original models to add tint
 * indices.
 */
@OnlyIn(Dist.CLIENT)
public class TieredModelGenerator {

    public static void generateAllModels(net.minecraft.server.packs.resources.ResourceManager resourceManager) {
        CreateTiers.LOGGER.info("Generating tiered models with grayscale textures and tinting...");

        DynamicResourcePack.clear();

        Map<ResourceLocation, JsonElement> models = new HashMap<>();
        Map<ResourceLocation, JsonObject> blockstates = new HashMap<>();

        for (Tier tier : TierRegistry.getAllTiers()) {
            generateTierModels(tier, models, blockstates, resourceManager);
        }

        models.forEach(DynamicResourcePack::addModel);
        blockstates.forEach(DynamicResourcePack::addBlockState);
        
        // Add creative tab name
        DynamicResourcePack.addTranslation("en_us", "itemGroup.createtiers", "Create Tiers");
        
        // Add tooltip labels
        DynamicResourcePack.addTranslation("en_us", "createtiers.tooltip.tiered_max_rpm", "Maximum Speed");
        DynamicResourcePack.addTranslation("en_us", "createtiers.tooltip.tiered_max_su", "Maximum Stress Capacity");
        
        DynamicResourcePack.markGenerated();
    }

    public static void generateTierModels(Tier tier, Map<ResourceLocation, JsonElement> models,
            Map<ResourceLocation, JsonObject> blockstates, net.minecraft.server.packs.resources.ResourceManager resourceManager) {
        String tierName = tier.getName();
        generateShaftModels(tierName, models, resourceManager);
        generateCogwheelShaftModel(tierName, models, resourceManager);
        generateCogwheelModels(tierName, false, models, resourceManager);
        generateCogwheelModels(tierName, true, models, resourceManager);
        generateItemModels(tierName, models);
        generateShaftBlockstate(tierName, blockstates);
        generateCogwheelBlockstate(tierName, false, blockstates);
        generateCogwheelBlockstate(tierName, true, blockstates);
        generateTierLanguages(tier);
    }

    private static void generateTierLanguages(Tier tier) {
        String tierName = tier.getName();
        String displayName = tier.getDisplayName();
        
        // Shaft
        DynamicResourcePack.addTranslation("en_us", "block.createtiers.shaft_" + tierName, displayName + " Shaft");
        
        // Cogwheel
        DynamicResourcePack.addTranslation("en_us", "block.createtiers.cogwheel_" + tierName, displayName + " Cogwheel");
        
        // Large Cogwheel
        DynamicResourcePack.addTranslation("en_us", "block.createtiers.large_cogwheel_" + tierName, "Large " + displayName + " Cogwheel");
    }

    private static void generateItemModels(String tierName, Map<ResourceLocation, JsonElement> models) {
        models.put(ResourceLocation.fromNamespaceAndPath(CreateTiers.MOD_ID, "models/item/shaft_" + tierName),
                createParentModel(CreateTiers.MOD_ID + ":block/" + tierName + "/shaft"));
        models.put(ResourceLocation.fromNamespaceAndPath(CreateTiers.MOD_ID, "models/item/cogwheel_" + tierName),
                createParentModel(CreateTiers.MOD_ID + ":block/" + tierName + "/cogwheel"));
        models.put(ResourceLocation.fromNamespaceAndPath(CreateTiers.MOD_ID, "models/item/large_cogwheel_" + tierName),
                createParentModel(CreateTiers.MOD_ID + ":block/" + tierName + "/large_cogwheel"));
    }

    private static JsonObject createParentModel(String parent) {
        JsonObject model = new JsonObject();
        model.addProperty("parent", parent);
        return model;
    }

    private static void generateShaftModels(String tierName, Map<ResourceLocation, JsonElement> models, net.minecraft.server.packs.resources.ResourceManager resourceManager) {
        Map<String, String> textures = Map.of(
                "0", CreateTiers.MOD_ID + ":block/grayscale/axis",
                "1", CreateTiers.MOD_ID + ":block/grayscale/axis_top",
                "particle", CreateTiers.MOD_ID + ":block/grayscale/axis");
        Map<String, Integer> tintMap = Map.of("Axis", 0);

        models.put(ResourceLocation.fromNamespaceAndPath(CreateTiers.MOD_ID, "models/block/" + tierName + "/shaft"),
                mutateModel(ResourceLocation.fromNamespaceAndPath("create", "block/shaft"), textures, tintMap, 0, Collections.emptySet(), resourceManager));
        models.put(
                ResourceLocation.fromNamespaceAndPath(CreateTiers.MOD_ID, "models/block/" + tierName + "/shaft_half"),
                mutateModel(ResourceLocation.fromNamespaceAndPath("create", "block/shaft_half"), textures, tintMap, 0, Collections.emptySet(), resourceManager));
    }

    private static void generateCogwheelShaftModel(String tierName, Map<ResourceLocation, JsonElement> models, net.minecraft.server.packs.resources.ResourceManager resourceManager) {
        // cogwheel_shaft uses textures 0=axis_top, 1=cogwheel_axis
        // We want the shaft part to use shaft color (tint 0)
        Map<String, String> textures = Map.of(
                "0", CreateTiers.MOD_ID + ":block/grayscale/axis_top",
                "1", CreateTiers.MOD_ID + ":block/grayscale/cogwheel_axis",
                "particle", CreateTiers.MOD_ID + ":block/grayscale/axis_top");
        // No named elements in cogwheel_shaft, so use default tint 0 (shaft color)
        Map<String, Integer> tintMap = Collections.emptyMap();

        models.put(ResourceLocation.fromNamespaceAndPath(CreateTiers.MOD_ID, "models/block/" + tierName + "/cogwheel_shaft"),
                mutateModel(ResourceLocation.fromNamespaceAndPath("create", "block/cogwheel_shaft"), textures, tintMap, 0, Collections.emptySet(), resourceManager));
    }

    private static void generateCogwheelModels(String tierName, boolean isLarge,
            Map<ResourceLocation, JsonElement> models, net.minecraft.server.packs.resources.ResourceManager resourceManager) {
        String suffix = isLarge ? "large_cogwheel" : "cogwheel";
        String gearTextureKey = isLarge ? "4" : "1_2";

        Map<String, String> textures = new HashMap<>();
        textures.put("0", CreateTiers.MOD_ID + ":block/grayscale/cogwheel_axis");
        textures.put("3", CreateTiers.MOD_ID + ":block/grayscale/axis_top");
        textures.put(gearTextureKey, CreateTiers.MOD_ID + ":block/grayscale/" + suffix);
        textures.put("particle", CreateTiers.MOD_ID + ":block/grayscale/" + suffix);

        Map<String, Integer> tintMap = new HashMap<>();
        tintMap.put("Axis", 0);
        tintMap.put("Gear", 1);
        tintMap.put("Gear2", 1);
        tintMap.put("Gear3", 1);
        tintMap.put("Gear4", 1);
        tintMap.put("Gear5", 1);
        tintMap.put("Gear6", 1);
        tintMap.put("Gear7", 1);
        tintMap.put("Gear8", 1);
        tintMap.put("GearCaseInner", 1);
        tintMap.put("GearCaseInnerRotated", 1);
        tintMap.put("GearCaseOuter", 1);

        models.put(ResourceLocation.fromNamespaceAndPath(CreateTiers.MOD_ID, "models/block/" + tierName + "/" + suffix),
                mutateModel(ResourceLocation.fromNamespaceAndPath("create", "block/" + suffix), textures, tintMap, 1, Collections.emptySet(), resourceManager));

        ResourceLocation shaftlessModelLoc = ResourceLocation.fromNamespaceAndPath(CreateTiers.MOD_ID, "models/block/" + tierName + "/" + suffix + "_shaftless");
        models.put(shaftlessModelLoc,
                mutateModel(ResourceLocation.fromNamespaceAndPath("create", "block/" + suffix + "_shaftless"), textures,
                        tintMap, 1, Collections.emptySet(), resourceManager));
        
        // Proactively register as PartialModel so it's loaded by the model manager
        // We use the path without 'models/' prefix as PartialModel adds it
        dev.engine_room.flywheel.lib.model.baked.PartialModel.of(ResourceLocation.fromNamespaceAndPath(CreateTiers.MOD_ID, "block/" + tierName + "/" + suffix + "_shaftless"));
    }

    private static JsonObject mutateModel(ResourceLocation baseModel, Map<String, String> textures,
            Map<String, Integer> tintMap, int defaultTint, Set<String> excludeElements, net.minecraft.server.packs.resources.ResourceManager resourceManager) {
        try {
            String[] parts = baseModel.toString().split(":");
            String namespace = parts[0];
            String path = parts[1];
            ResourceLocation modelLoc = ResourceLocation.fromNamespaceAndPath(namespace, "models/" + path + ".json");
            java.util.Optional<net.minecraft.server.packs.resources.Resource> resource = resourceManager.getResource(modelLoc);
            if (resource.isEmpty()) {
                CreateTiers.LOGGER.error("Could not find base model to mutate: {}", modelLoc);
                return new JsonObject();
            }

            JsonObject model = JsonParser.parseReader(new InputStreamReader(resource.get().open(), StandardCharsets.UTF_8))
                    .getAsJsonObject();

            JsonObject texturesObj = new JsonObject();
            textures.forEach(texturesObj::addProperty);
            model.add("textures", texturesObj);

            if (model.has("elements")) {
                JsonArray elements = model.getAsJsonArray("elements");
                JsonArray newElements = new JsonArray();
                for (JsonElement el : elements) {
                    JsonObject element = el.getAsJsonObject();
                    String name = element.has("name") ? element.get("name").getAsString() : "";
                    
                    if (excludeElements.contains(name)) continue;
                    
                    int tintIndex = tintMap.getOrDefault(name, defaultTint);

                    if (element.has("faces")) {
                        JsonObject faces = element.getAsJsonObject("faces");
                        for (String faceName : faces.keySet()) {
                            faces.getAsJsonObject(faceName).addProperty("tintindex", tintIndex);
                        }
                    }
                    newElements.add(element);
                }
                model.add("elements", newElements);
            }

            return model;
        } catch (Exception e) {
            CreateTiers.LOGGER.error("Failed to mutate model: " + baseModel, e);
            return new JsonObject();
        }
    }

    private static void generateShaftBlockstate(String tierName, Map<ResourceLocation, JsonObject> blockstates) {
        ResourceLocation modelLocation = ResourceLocation.fromNamespaceAndPath(CreateTiers.MOD_ID,
                "block/" + tierName + "/shaft");
        blockstates.put(ResourceLocation.fromNamespaceAndPath(CreateTiers.MOD_ID, "blockstates/shaft_" + tierName),
                createAxisBlockstate(modelLocation));
    }

    private static void generateCogwheelBlockstate(String tierName, boolean isLarge,
            Map<ResourceLocation, JsonObject> blockstates) {
        String suffix = isLarge ? "large_cogwheel" : "cogwheel";
        ResourceLocation modelLocation = ResourceLocation.fromNamespaceAndPath(CreateTiers.MOD_ID,
                "block/" + tierName + "/" + suffix);
        blockstates.put(
                ResourceLocation.fromNamespaceAndPath(CreateTiers.MOD_ID, "blockstates/" + suffix + "_" + tierName),
                createAxisBlockstate(modelLocation));
    }

    private static JsonObject createAxisBlockstate(ResourceLocation model) {
        JsonObject blockstate = new JsonObject();
        JsonObject variants = new JsonObject();
        for (Direction.Axis axis : Direction.Axis.values()) {
            for (boolean waterlogged : new boolean[] { false, true }) {
                JsonObject variant = new JsonObject();
                variant.addProperty("model", model.toString());
                if (axis == Direction.Axis.X) {
                    variant.addProperty("x", 90);
                    variant.addProperty("y", 90);
                } else if (axis == Direction.Axis.Z) {
                    variant.addProperty("x", 90);
                }
                variants.add("axis=" + axis.getName() + ",waterlogged=" + waterlogged, variant);
            }
        }
        blockstate.add("variants", variants);
        return blockstate;
    }
}
